package com.bit.mybatis.domain;


import java.io.Serializable;
import java.util.Date;

/**
 * null
 * @TableName file_records
 */
public class FileRecords implements Serializable {
    /**
     *
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private String fileId;

    /**
     * 桶名称
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private String bucket;

    /**
     * 对象名称
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private String object;

    /**
     * md5
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private String md5;

    /**
     * 文件名称
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private String fileName;

    /**
     * 分享url
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private String shareUrl;

    /**
     * 上传url
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private String uploadUrl;

    /**
     * 总大小
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private Long size;

    /**
     * 文件类型
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private String fileType;

    /**
     * 分片进度索引
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private Long chunkProgessIndex;

    /**
     * 分片标识 0 否 1 是
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private String chunkFlag;

    /**
     * 块数量
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private Long chunkNum;

    /**
     * 上传耗时
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private Long totalChunkTime;

    /**
     * 0 未上传 1 已上传  2 已删除
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private Integer fileFlag;

    /**
     * 创建日期
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private Date createDate;

    /**
     * 更新日期
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_records
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public String getFileId() {
        return fileId;
    }

    /**
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * 桶名称
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public String getBucket() {
        return bucket;
    }

    /**
     * 桶名称
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setBucket(String bucket) {
        this.bucket = bucket;
    }

    /**
     * 对象名称
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public String getObject() {
        return object;
    }

    /**
     * 对象名称
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setObject(String object) {
        this.object = object;
    }

    /**
     * md5
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public String getMd5() {
        return md5;
    }

    /**
     * md5
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    /**
     * 文件名称
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * 文件名称
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * 分享url
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public String getShareUrl() {
        return shareUrl;
    }

    /**
     * 分享url
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl;
    }

    /**
     * 上传url
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public String getUploadUrl() {
        return uploadUrl;
    }

    /**
     * 上传url
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setUploadUrl(String uploadUrl) {
        this.uploadUrl = uploadUrl;
    }

    /**
     * 总大小
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public Long getSize() {
        return size;
    }

    /**
     * 总大小
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * 文件类型
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * 文件类型
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * 分片进度索引
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public Long getChunkProgessIndex() {
        return chunkProgessIndex;
    }

    /**
     * 分片进度索引
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setChunkProgessIndex(Long chunkProgessIndex) {
        this.chunkProgessIndex = chunkProgessIndex;
    }

    /**
     * 分片标识 0 否 1 是
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public String getChunkFlag() {
        return chunkFlag;
    }

    /**
     * 分片标识 0 否 1 是
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setChunkFlag(String chunkFlag) {
        this.chunkFlag = chunkFlag;
    }

    /**
     * 块数量
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public Long getChunkNum() {
        return chunkNum;
    }

    /**
     * 块数量
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setChunkNum(Long chunkNum) {
        this.chunkNum = chunkNum;
    }

    /**
     * 上传耗时
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public Long getTotalChunkTime() {
        return totalChunkTime;
    }

    /**
     * 上传耗时
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setTotalChunkTime(Long totalChunkTime) {
        this.totalChunkTime = totalChunkTime;
    }

    /**
     * 0 未上传 1 已上传  2 已删除
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public Integer getFileFlag() {
        return fileFlag;
    }

    /**
     * 0 未上传 1 已上传  2 已删除
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setFileFlag(Integer fileFlag) {
        this.fileFlag = fileFlag;
    }

    /**
     * 创建日期
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * 创建日期
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * 更新日期
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * 更新日期
     *
     * @mbg.generated 2021-03-09 22:40:51
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Override
    public String toString() {
        return "FileRecords{" +
                "fileId='" + fileId + '\'' +
                ", bucket='" + bucket + '\'' +
                ", object='" + object + '\'' +
                ", md5='" + md5 + '\'' +
                ", fileName='" + fileName + '\'' +
                ", shareUrl='" + shareUrl + '\'' +
                ", uploadUrl='" + uploadUrl + '\'' +
                ", size=" + size +
                ", fileType='" + fileType + '\'' +
                ", chunkProgessIndex=" + chunkProgessIndex +
                ", chunkFlag='" + chunkFlag + '\'' +
                ", chunkNum=" + chunkNum +
                ", totalChunkTime=" + totalChunkTime +
                ", fileFlag=" + fileFlag +
                ", createDate=" + createDate +
                ", updateDate=" + updateDate +
                '}';
    }
}